### ISSUE TITLE
SettingsMenuDrawerOnItemClickedListener onClick using TintContextWrapper instead of an Activity context.

### ISSUE THREAD

**Issue by WolfganP** [NineWorlds/serenity-android#365] opened 2017-09-08 17:57 UTC
I'm using a chinese Android 4.4.2 box (that presents to apps as a tablet) connected to a HDTV, and while I have no issues using my Plex library thru DLNA, I want to improve my setup (leanback navigation, richer UI) using a Plex client, and fortunately I found Serenity.

My problem is that I tried both v 2.0.0M2 and v1.9.5M1 (downloaded from the wiki) and the app starts, finds my Plex server, but then any attempt to navigate the menus or even enter app Settings crash the app ("Unfortunately app has stopped").

I understand that the apps' versions I tried support my OS v4.4.2. Logs via aLogcat verbose filtered by 'serenity' below. 
Any tip? Or I missing something extremely obvious and the app is not intended for my environment?
Thx in advance.

```
E/AndroidRuntime( 4886): Process: us.nineworlds.serenity, PID: 4886
E/AndroidRuntime( 4886): java.lang.RuntimeException: Unable to start activity ComponentInfo{us.nineworlds.serenity/us.nineworlds.serenity.ui.browser.movie.MovieBrowserActivity}: java.lang.NullPointerException
I/DEBUG   ( 4932): [OnPurpose Redunant in preset_info] pid: 4886, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
E/AndroidRuntime( 5372): Process: us.nineworlds.serenity, PID: 5372
E/AndroidRuntime( 5372): java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to us.nineworlds.serenity.ui.activity.SerenityDrawerLayoutActivity
E/AndroidRuntime( 5372): 	at us.nineworlds.serenity.ui.listeners.SettingsMenuDrawerOnItemClickedListener.onClick(SettingsMenuDrawerOnItemClickedListener.java:43)
I/DEBUG   ( 5427): [OnPurpose Redunant in preset_info] pid: 5372, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
E/InputDispatcher(  652): channel '42333830 us.nineworlds.serenity/us.nineworlds.serenity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/AndroidRuntime( 5436): Process: us.nineworlds.serenity, PID: 5436
E/AndroidRuntime( 5436): java.lang.RuntimeException: Unable to start activity ComponentInfo{us.nineworlds.serenity/us.nineworlds.serenity.ui.browser.movie.MovieBrowserActivity}: java.lang.NullPointerException
I/DEBUG   ( 5491): [OnPurpose Redunant in preset_info] pid: 5436, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
```

**Comment by kingargyle** [comment] 2017-09-08 18:09
This is a bug with how the context new App Compat library wraps the context.  I know what the fix for this is, so I'll target this before I release 2.0.0-M3.  @WolfganP  I should have a fix in the next day or so and hope to release 2.0.0-M3 this weekend for testing.  Thanks for reporting the issue.

**Comment by kingargyle** [comment] 2017-09-08 18:11
Also, 2.0.0-M3 will bring better video playback and coding support as well as basic Transcoding support for Plex.  So I would stick with the 2.x series going forward.

**Comment by WolfganP** [comment] 2017-09-08 18:22
Thanks @kingargyle , I'll switch to the v2 branch then, I understood the tablet features were going to disappear and being my box an old OS one, I went for the "more stable" branch :-)
Let me know if you need additional info or test.

BTW, in order to obtain the logs I had to get info from different issues around, did you consider writing a a targeted wiki article? (ie pointing to the preferred logcat app, log level needed, filter to use, etc)
Thanks!

**Comment by WolfganP** [comment] 2017-09-08 18:31
BTW, v2.0.0-M2 log trying to access the app Settings pasted below just in case it's a different issue (in v2 case, the background remains with Serenity logo, and menu never goes on color as v1.95).

```
E/AndroidRuntime( 4886): Process: us.nineworlds.serenity, PID: 4886
E/AndroidRuntime( 4886): java.lang.RuntimeException: Unable to start activity ComponentInfo{us.nineworlds.serenity/us.nineworlds.serenity.ui.browser.movie.MovieBrowserActivity}: java.lang.NullPointerException
I/DEBUG   ( 4932): [OnPurpose Redunant in preset_info] pid: 4886, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
E/AndroidRuntime( 5372): Process: us.nineworlds.serenity, PID: 5372
E/AndroidRuntime( 5372): java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to us.nineworlds.serenity.ui.activity.SerenityDrawerLayoutActivity
E/AndroidRuntime( 5372): 	at us.nineworlds.serenity.ui.listeners.SettingsMenuDrawerOnItemClickedListener.onClick(SettingsMenuDrawerOnItemClickedListener.java:43)
I/DEBUG   ( 5427): [OnPurpose Redunant in preset_info] pid: 5372, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
E/InputDispatcher(  652): channel '42333830 us.nineworlds.serenity/us.nineworlds.serenity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
E/AndroidRuntime( 5436): Process: us.nineworlds.serenity, PID: 5436
E/AndroidRuntime( 5436): java.lang.RuntimeException: Unable to start activity ComponentInfo{us.nineworlds.serenity/us.nineworlds.serenity.ui.browser.movie.MovieBrowserActivity}: java.lang.NullPointerException
I/DEBUG   ( 5491): [OnPurpose Redunant in preset_info] pid: 5436, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
E/InstalledAppDetails( 5983): Exception when retrieving package:us.nineworlds.serenity
E/InstalledAppDetails( 5983): android.content.pm.PackageManager$NameNotFoundException: us.nineworlds.serenity
E/ProcessKiller(  147): Process com.android.packageinstaller (6097) has open file /storage/usbotg/usbotg-sda1/serenity-app-2.0.0-m2.apk
E/ProcessKiller(  147): Process com.android.packageinstaller (6097) has open file /storage/usbotg/usbotg-sda1/serenity-app-2.0.0-m2.apk
E/ProcessKiller(  147): Process com.android.packageinstaller (6097) has open file /storage/usbotg/usbotg-sda1/serenity-app-2.0.0-m2.apk
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.GlideClearCacheJob@41fb8740
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.GlideClearCacheJob.onRun(GlideClearCacheJob.java:35)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/JobManager( 6740): error while executing job us.nineworlds.serenity.jobs.MainMenuRetrievalJob@41ee1308
E/JobManager( 6740): 	at us.nineworlds.serenity.jobs.MainMenuRetrievalJob.onRun(MainMenuRetrievalJob.java:33)
E/AndroidRuntime( 6740): Process: us.nineworlds.serenity, PID: 6740
E/AndroidRuntime( 6740): java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to us.nineworlds.serenity.ui.activity.SerenityDrawerLayoutActivity
E/AndroidRuntime( 6740): 	at us.nineworlds.serenity.ui.listeners.SettingsMenuDrawerOnItemClickedListener.onClick(SettingsMenuDrawerOnItemClickedListener.java:44)
I/DEBUG   ( 6786): [OnPurpose Redunant in preset_info] pid: 6740, tid: -1361051648, name: UNKNOWN  >>> us.nineworlds.serenity <<<
```

**Comment by kingargyle** [comment] 2017-09-08 18:42
For the Serenity Logo staying around, if you Navigate Up to the Menu icon, and then Navigate back down, the Grid will get the focus.   Sometimes for some reason the Grid doesn't always get the focus even though it requests it.  It is something that randomly happens on various platforms.   Doing the slight navigation should get the backround to trigger.

It also looks like you are getting a couple of other errors when trying to retrieve the Menu.  I'll see if I can get the SettingsMenuDrawerOnItemClicked list issue fixed first and we can try to address the other issues you are having after that.

**Comment by kingargyle** [comment] 2017-09-09 00:18
The cause of the crash show now be fixed.  I pushed the changes to the develop branch.  I'll include this in the 2.0.0-M3 build I'll post later tonight.

**Comment by kingargyle** [comment] 2017-09-09 00:20
Also as for the statement that Tablets won't be supported, it is mainly because of the extension of the RecyclerView library I'm using that isn't Touch Screen aware, but if you have a DPAD, Remote Control, Keyboard, or game controller linked by Bluetooth to a Tablet... the Serenity should still work.  I just want to set appropriate expectations for users of 2.0.

**Closed** 2017-09-09 00:20 UTC
Labels: bug, IN PROGRESS
