### ISSUE TITLE
Grid view and detail view crash in tablet me302c Android 4.3

### ISSUE THREAD

**Issue by davboc** [NineWorlds/serenity-android#302] opened 2015-08-06 11:32 UTC
Hi!

I have this problem with tablet me302c and Android 4.3. When I switch the view to grid view or detail view the app crash and restart, so I can't see the grid view list...
I downloaded latest version of Serenity, hope that there is a solution because I really need something that auto-update the watched status with an external player like mx player.
I can provide a logcat of the crash if this can be useful.

Thanks for reading and for the support.

Bye

Davide

**Comment by kingargyle** [comment] 2015-08-06 14:09
https://github.com/NineWorlds/serenity-android/wiki/Serenity-for-Android#bugreports

Please provide me the information in that list, particularly the movies.  I'll also check my Google Analytics account to see if it has a crash report there with the stack trace.

**Comment by davboc** [comment] 2015-08-06 15:50
http://wikisend.com/download/179150/serenity.zip

In that archive I put all files requests, and also add a logcat of the error.

Other details: 
The section 1 contains films, the section 2 tv shows. In the section 1 app crash either that I select grid view or details view, but when I click on the section I can see all movies in details view, so the strange is that I can see details view but if I tap on "details view" the app crash. In the section 2, tv shows, I can select grid view or details view without any crash.

The section 1 now contain many movies, but at first I tried with only two movies and the app crashed at the same way.

If I can provide other informantions please ask me, I'm glad to help this project

Thanks for reply and for the help

**Comment by kingargyle** [comment] 2015-08-06 16:31
Usually in this case, if it is crashing in both sections, there is probably missing data that the app expects to be filled in.  Haven't seen this for a while but the sample files will help.

**Comment by davboc** [comment] 2015-08-06 17:08
I tried to create a film section named "test" in a folder with only one video file: the problem is the same, indipendently from the movie that I put in this folder, so I think that the problem is in the "video" type of the section...

**Comment by kingargyle** [comment] 2015-08-06 17:25
Stack trace was in the logcat,  so it is definitely a NullPointer exception. 

java.lang.NullPointerException
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at us.nineworlds.serenity.ui.browser.movie.MovieMenuDrawerOnItemClickedListener.onItemClick(MovieMenuDrawerOnItemClickedListener.java:96)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.widget.AdapterView.performItemClick(AdapterView.java:297)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2793)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.widget.AbsListView$1.run(AbsListView.java:3468)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.os.Handler.handleCallback(Handler.java:730)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.os.Handler.dispatchMessage(Handler.java:92)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.os.Looper.loop(Looper.java:150)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at android.app.ActivityThread.main(ActivityThread.java:5162)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at java.lang.reflect.Method.invoke(Method.java:525)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
08-06 12:46:09.652: E/AndroidRuntime(9840): 	at dalvik.system.NativeStart.main(Native Method)
08-06 12:46:09.652: W/ActivityManager(451):   Force finishing activity us.nineworlds.serenity/.ui.browser.movie.MovieBrowserActivity

The issue doesn't appear to be with the content of your video files, but for some reason it can't find the Adapter that it needs for gridview.

https://github.com/NineWorlds/serenity-android/blob/master/serenity-app/src/main/java/us/nineworlds/serenity/ui/browser/movie/MovieMenuDrawerOnItemClickedListener.java#L96

**Comment by davboc** [comment] 2015-08-06 17:27
and then what can I do?

Thanks again for your kindness

**Comment by kingargyle** [comment] 2015-08-06 17:30
Okay, so let's try the following:

Can you go to the System Settings->Application Manager->Serenity for Android->Clear Data.

Then try restarting the application.  This should set everything back to the default state, unfortunately you'll lose any custom settings and cached data.   The app should be in a state where it is in Details view for videos.   Select your Movies folder, and hopefully it comes up and displays.  If it doesn't grab the logcat and we will see what it is trying to do at that point.

if it does display, go back to the main menu and then back into the Movies folder, then try clicking the Grid view.

Because I don't have the particular device you have and are having problems with It is going to be bit difficult for me to replicate why this is happening.

**Comment by davboc** [comment] 2015-08-06 17:38
No luck :( same problem.

http://wikisend.com/download/394502/logcat.zip

I've attached two different log: one for error in grid view and the other for error in details view.

Thanks again

**Comment by kingargyle** [comment] 2015-08-06 18:04
Okay, the Details view stack trace is in the same area:

java.lang.NullPointerException
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at us.nineworlds.serenity.ui.browser.movie.MovieMenuDrawerOnItemClickedListener.onItemClick(MovieMenuDrawerOnItemClickedListener.java:101)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.widget.AdapterView.performItemClick(AdapterView.java:297)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2793)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.widget.AbsListView$1.run(AbsListView.java:3468)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.os.Handler.handleCallback(Handler.java:730)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.os.Handler.dispatchMessage(Handler.java:92)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.os.Looper.loop(Looper.java:150)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at android.app.ActivityThread.main(ActivityThread.java:5162)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at java.lang.reflect.Method.invoke(Method.java:525)
08-06 19:36:18.419: E/AndroidRuntime(14290): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)

May take me a bit to get something, but will try to get to it this weekend.

**Comment by kingargyle** [comment] 2015-08-06 18:08
One more question are you getting this as soon as you click, the Movie folder option from the screen?  As this MovieOnClickMenuItem should only fire, if you specifically select the Menu once the items are loaded and displayed.

Can you tell me the sequence of events so i can try to replicate the issue?  Thanks.

**Comment by davboc** [comment] 2015-08-06 18:44
When I open the app i see the horizontal menu with the name of sections. I click on one section (film) and I can see without problem the film in details view. If I open the side menu whatever I click causes the error, so If I click "grid view" the app crash, if I click the details view (that is what I see actually) the app crash.

If, in settings, I select "Movie Grid poster layout" the app crash immediatly after I click on the section, so in this case I can't see movies.

Thanks again for everything

**Comment by kingargyle** [comment] 2015-08-06 19:45
Thanks.  I've been seeing occasionally error reports around this situation, but have never had anybody give me steps to try and reproduce.  I'll try re-working the way I do the Fragment switching on those screens.  Hopefully I'll have a development build for you test out this weekend.

**Comment by davboc** [comment] 2015-08-06 19:49
perfect! Thank you very much!

**Comment by davboc** [comment] 2015-08-07 00:48
while we're at, some other little problem that I found.

1) I have a little nas, with a little cpu. I see that movies in details view launch some queries at every horizontal scroll, this because it must load description, background etc... If I scroll many movies at time the process of plex on the nas is supendend, so I must stop the process and relaunch it... I think that if you can enable the grid view you solve this problem too, but I report it anyway

2) If i start to see a video, exit and want to reset watched status to unwatched tap on the toggle one time, and it mark the movie as watched, but if I tap again for set to unwatched it doesn't work, so I need to exit and re-enter in the section to complete the operation. Maybe a double option "mark as watched" and "mark as unwatched" could work better...

3) I can't use search in the first page, every word I insert gives me zero results.

Thanks again

bye!

**Comment by kingargyle** [comment] 2015-08-11 19:24
Thanks.  I unforunately didn't get to this, this last weekend.  I had to do a Release on the Eclipse Andmore project.  I should have time to look at this, I'm also hoping to get Unviversal Transcoder support added as well.

**Comment by davboc** [comment] 2015-08-20 12:18
please do not forget me :)

**Comment by kingargyle** [comment] 2015-08-20 18:59
I haven't....just trying to carve time out.

**Comment by davboc** [comment] 2015-08-20 19:01
Thanks mate

**Comment by davboc** [comment] 2015-08-21 12:03
Another improvement that could be useful is the automatic update of watched status after exit of playing video, indeed actually I need to come back and re-enter to the section to view the watched status updated.

**Comment by kingargyle** [comment] 2015-08-21 15:01
The update of watch status should already happen.  Are you using an External player?   If you use MX Player it should update watch status and position when you exit playing.   The internal player should also support this.

**Comment by davboc** [comment] 2015-08-21 15:05
Yes I didn't say that doesn't work, but at the and of the movie if I exit from Mx player the page of Serenity is the same as when I started to watch the movie, so expecially for tv series I need to come back and re-enter in the section for update the last viewed status. 

It's a minor update but maybe you can solve this without much work.

**Comment by kingargyle** [comment] 2015-08-21 15:15
Hmm...it should just update when it gets back.  I'm planning some pretty big rework around the whole app due to me migrating away from Google TV, so this area may be touched, as I might be able to leverage the Universal Transcoder which would allow the internal player to be used and not necessarily require MX Player any longer.

**Comment by kingargyle** [comment] 2015-08-23 21:50
Targeting for 1.9.4.  Let's see how much I can clean up.

**Comment by kingargyle** [comment] 2015-08-24 01:51
Well didn't make much progress as I was getting into it...I got interrupted.  Will try again.

**Comment by davboc** [comment] 2015-08-24 11:34
I actually use 1.9.4 version from play store, no differences

**Comment by kingargyle** [comment] 2015-08-24 13:04
Yeah. my mistake it should be 1.9.5, not 1.9.4

**Comment by davboc** [comment] 2015-08-30 23:48
about that:
----------------
Hmm...it should just update when it gets back. I'm planning some pretty big rework around the whole app due to me migrating away from Google TV, so this area may be touched, as I might be able to leverage the Universal Transcoder which would allow the internal player to be used and not necessarily require MX Player any longer.
----------------

I see that in the movie categories all works weel, so the watched status is updated when I go back from mx player. The problem is in the TV series categories, here for update the watched status I need to go back again and enter again in the season of the series.

**Comment by kingargyle** [comment] 2015-09-01 16:12
Thanks for the clarification.  Still trying to get time to address this and some other issues.

**Comment by davboc** [comment] 2015-09-12 09:59
I'll try to describe another bug.... I'm sorry in advance for my bad English.

First of all, another detail of my previous report: when I enter in a tv series I can see a list of the seasons in the bottom if the page and I can swype it and see episodes in the top of the page, from this view if I start to see an episode its watched status is rightly flagged when I come back from mx player, instead if I tap on a season below and enter in a list of episodes that I can swype, there the watched status is not immediatly reported when I exit from mx player.

This is the bug: In the Tv series category where there are the list of seasons in the bottom, if  I start to see episode E01, at the end of the view I come back from mx player and the E01 episode is rightly flagged as "watched", so I start to see E02 without come back from the episodes view, I see it until the minute 10. Now, if I come back from mx player,  E02 is still flagged as unwatched but the E01 is flagged as "partial watched until minute 10"...

I'm sorry for this long list of bugs, I know that you can't solve all, but I use this app everyday (I really hate the plex app that doesn't update watched status with mxplayer) and if I find something wrong I report it there, maybe the solution is more immediate than I think.

However thanks for your support and kindness

**Comment by kingargyle** [comment] 2015-09-14 12:50
That is a an odd one.  Thanks for reporting it.

**Comment by davboc** [comment] 2015-10-13 19:00
No news, mate?

**Comment by kingargyle** [comment] 2015-10-13 19:28
Sorry haven't had much time to work on anything.

**Comment by davboc** [comment] 2016-02-20 20:59
sorry mate, you have completely abandoned this project? Or I can hope that you'll come back one day?

**Comment by kingargyle** [comment] 2016-02-23 15:33
Nope, haven't abandonded it.  I just haven't had time to work on it.  For most uses cases it functions as is.   I do want to update it for Leanback for the tvs, but life keeps getting in the way.

**Comment by kingargyle** [comment] 2016-03-18 15:30
will be replacing these views with Recycler views so this is related to #308 which will replace the horizontal gridview with corresponding recycler view implementations.

**Comment by kingargyle** [comment] 2017-03-09 18:20
Closing this as Recycler View is now being used instead of the old Gallery and TwoWayViews.   Should be addressed in the 2.0.x branch.

**Closed by kingargyle** 2017-03-09 18:20 UTC
Labels: Amazon Fire TV, AndroidTV, bug
